# Site Settings
title: Lunr
email: 
description: >
  A bit like Solr, but much smaller and not as bright
baseurl: ""
url: "http://localhost:4000"
twitter_username: scottjhorn
github_username:  sjhorn
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM